server:
  port: 8100
eureka:
  server:
    # 本地关闭自我保护
    enable-self-preservation: false
  instance:
    hostname: 127.0.0.1
  client:
    # 不用检索服务
    fetch-registry: false
    # 不向注册中心注册自己
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
